private_saas/apps/uprofile/urls.py
from django.conf.urls.defaults import *

from uprofile import views

urlpatterns = patterns('',
    url(r'^$', views.profile__index, name='profile-index'),
    url(r'^login/$',  views.profile__login, name='profile-login'),
    url(r'^logout/$', views.profile__logout, name='profile-logout'),
    url(r'^register/$', views.profile__register, name='profile-register'),
    url(r'^reset/$',  views.profile__reset_password, name='profile-password-reset'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
          views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
    url(r'^change-password/$', views.password_change, name='profile-change-password'),

    url(r'^payment/$', views.profile__payment__payform, name='profile-payment-index'),
    url(r'^payment/payform/$', views.profile__payment__payform, name='profile-payment-payform'),
    url(r'^payment/success/$', views.profile__payment__success, name='profile-payment-success'),
    url(r'^payment/fail/$', views.profile__payment__fail, name='profile-payment-fail'),

    url(r'^payment/promocode/$', views.profile__payment__promocode, name='profile-payment-promocode-form'),



    url(r'^history/$', views.profile__history, name='profile-history-index'),
    url(r'^feedback/$', views.profile__feedback, name='profile-feedback-form'),

    #url(r'^sub/', include('subscription.urls')),
)

private_saas/apps/uprofile/forms.py
from django import forms
from django.contrib.auth.models import User
try:
    from django.contrib.auth.utils import UNUSABLE_PASSWORD
except:
    UNUSABLE_PASSWORD = '!'
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.utils.http import int_to_base36
from django.utils.translation import ugettext_lazy as _
from django.template import loader

class PasswordResetForm(forms.Form):
    username = forms.CharField(max_length=30)

    def clean_username(self):
        username = self.cleaned_data["username"]
        self.users_cache = User.objects.filter(
                                username__exact=username,
                                is_active=True)
        if not len(self.users_cache):
            raise forms.ValidationError(_("That username doesn't have an associated user account. Are you sure you've registered?"))
        if any((user.password == UNUSABLE_PASSWORD) for user in self.users_cache):
            raise forms.ValidationError(_("The user account associated with this e-mail address cannot reset the password."))
        return username

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the user
        """
        from django.core.mail import send_mail
        for user in self.users_cache:
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': int_to_base36(user.id),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': use_https and 'https' or 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])

class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set his/her password without
    entering the old password
    """
    new_password1 = forms.CharField(label=_("New password"), widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=_("New password confirmation"), widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

class PasswordChangeForm(SetPasswordForm):
    pass

private_saas/apps/uprofile/templates/uprofile/layouts/personal/change_password_form.html
{% load i18n %}

<div class="fm">
    <form action="{% url profile-change-password %}" method="post">
        {% csrf_token %}

        <div class="fm__row">
            <label for="id_new_password1">{{password_change_form.new_password1.label}}</label>
        </div>
        <div class="fm__row">{{password_change_form.new_password1}}</div>

        <div class="fm__row">
            <label for="id_new_password2">...{% trans 'confirmation' %}</label>
        </div>
        <div class="fm__row">{{password_change_form.new_password2}}</div>
        <div class="fm__hspacer"></div>

        <div class="fm__row">
            <input type="button" onclick="return UProfile.change_password(this);"
                    value="{% trans 'Change Password' %}" />
        </div>
    </form>
</div>

private_saas/apps/uprofile/templates/uprofile/layouts/personal/index.html
{% load i18n %}
{% load invitation %}
{% load payment %}

<div id="profile__me" class="profile__block">
    <div class="profile__me__wrap wrap">
        <h2 class="title">{% trans 'Personal' %}</h2>
        <ul class="profile__me__general">
            <li class="first col width-30">
                <span class="key">{% trans 'Your email' %}:</span>
                <span class="val">{{user.email}}</span>
            </li>
            <li class="col width-30">
                <span class="key">{% trans 'Invited by' %}:</span>
                <span class="val">{% invited_by %}</span>
            </li>
            <li class="last col width-40">
                <span class="key">{% trans 'Paid days' %}:</span>
                <span class="val">{% paid_days %}</span>
            </li>
        </ul>
    </div>
    <div class="profile__me__separator"></div>
    <div class="profile__me__wrap wrap">
        <div class="col width-50">
            <h2 class="title">{% trans 'Change password' %}</h2>

            {% include 'uprofile/layouts/personal/change_password_form.html' %}
        </div>
        <div class="col width-50">
            <h2 class="title">{% trans 'Invites' %}</h2>
            <div class="fm__help">When paying by registered users according to the codes on your account will be credited with a certain number of bonus days.</div>

            {% for ui in user.invitations.all %}
                {% if ui.valid %}
                <div class="fm__row">
                    <h3>{{ui.key}}</h3>
                    <p>{% trans 'estimate' %}: {{ui.estimate}}</p>
                </div>
                {% endif %}
            {% empty %}
                <div class="fm__help">{% trans 'No invitation.' %}</div>
            {% endfor %}
        </div>
    </div>
</div>